# 配置tomcat端口号
server:
  port: 8080

# 配置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx_db
    username: root
    password: root

# 配置mybatis
mybatis:
  # 配置类型别名包扫描
  type-aliases-package: com.xxx.xxx.pojo
  # 配置sql语句映射文件路径
  mapper-locations:
    - classpath:mappers/*.xml
  # 驼峰映射
  configuration:
    map-underscore-to-camel-case: true

# 配置日志
logging:
  level:
    com.xxx: debug